fixes unit test failure for publish local path on windows
vmware-tanzu/apps-cli-plugin pull request #350
Opened 2022-09-23 22:39 UTC by shaheerkootteeri

Pull request

### What this PR does / why we need it

PR fixes unit test failure for publish local path on windows. the img manifest is showing different in windows and mac when publishing local source with excluded files. 
### Which issue(s) this PR fixes

Fixes #349 

### Describe testing done for PR

Unit tests validated in mac as well as windows. 

### Additional information or special notes for your reviewer

2022-09-23 23:00 UTC, shashwathi commented on pkg/commands/workload_test.go
> +	excludedFilesImgMnfst := "fedc574423e7aa2ecdd2ffb3381214e3c288db871ab9a3758f77489d6a777a1d"
can you rename to `expectedImageDigest`?

2022-09-29 16:06 UTC, odinnordico requested changes

2022-09-29 21:10 UTC, shashwathi reviewed
this PR is doing 2 things
- updating hard coded file paths to using filepath lib
- adding test (that gets skipped in windows) 

I recommend keeping the goal of a PR to one item. Easy to review and revert.

2022-09-29 21:13 UTC, shaheerkootteeri commented on pkg/commands/workload_test.go
> +	runtm "runtime"
Updated the code

2022-09-30 15:16 UTC, odinnordico submitted a review, later dismissed

2022-10-01 13:52 UTC, shashwathi approved these changes

2022-10-01 14:07 UTC, merged