Add namespace to workload get overview section
vmware-tanzu/apps-cli-plugin pull request #357
Opened 2022-09-29 16:43 UTC by warango4

Pull request

### What this PR does / why we need it
Add namespace to workload get output in Overview section

### Which issue(s) this PR fixes

Fixes #321 

### Describe testing done for PR

- Updated unit testing

### Additional information or special notes for your reviewer

Signed-off-by: Wendy Arango <warango@vmware.com>

2022-09-29 16:52 UTC, warango4 commented
![image](https://user-images.githubusercontent.com/22118549/193091748-1af4a1d6-6bd8-4f57-ac4a-c7e4580771db.png)

2022-09-29 16:54 UTC, warango4 commented
![image](https://user-images.githubusercontent.com/22118549/193092129-5b1000da-7962-4b61-aeb5-8ce97829bf88.png)

2022-09-30 15:32 UTC, odinnordico requested changes
Please update docs

2022-10-01 14:08 UTC, shashwathi reviewed
looks good. Update docs as mentioned in other comment.

2022-10-03 00:36 UTC, shaheerkootteeri reviewed
LGTM

2022-10-04 17:06 UTC, shashwathi commented on docs/commands-details/workload_get.md
> +- An overview section, where workload name, type and namespace where it's located are displayed.
`workload name, type and namespace are displayed.`

2022-10-04 17:06 UTC, shashwathi commented on docs/commands-details/workload_get.md
> +At the very end of the command output, a hint to follow up commands is also shown.
keep the word `displayed`

2022-10-04 19:41 UTC, odinnordico approved these changes

2022-10-04 19:50 UTC, merged