fixes paths in workload test file to use filepath library
vmware-tanzu/apps-cli-plugin pull request #358
Opened 2022-09-30 19:57 UTC by shaheerkootteeri

Pull request

### What this PR does / why we need it
PR fixes the paths in the workload test file to use filepath library to make OS agnostic 

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

Tested unit test cases in both Mac as well as windows machine 

### Additional information or special notes for your reviewer

2022-09-30 21:53 UTC, odinnordico requested changes

2022-09-30 21:53 UTC, odinnordico commented on pkg/commands/workload_test.go
> +	localRepo := filepath.Join(string(filepath.Separator), "path", "to", "local", "repo")
can `string(filepath.Separator)` be a global const/var to not cal `string(...)` each time?

2022-10-01 13:48 UTC, shashwathi approved these changes

2022-10-03 16:12 UTC, odinnordico submitted a review, later dismissed

2022-10-03 17:15 UTC, shashwathi approved these changes

2022-10-03 17:15 UTC, merged